CREATE DATABASE PAULINO;

USE PAULINO;

CREATE TABLE TURMAS (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_TURMA VARCHAR(100) NOT NULL,
    SERIE CHAR(20) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Turmas que serão disponiveis no site';

CREATE TABLE PROFESSORES (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(160) NOT NULL,
    SENHA VARCHAR(16) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Profesores responsáveis por lecionar as aulas';

CREATE TABLE MATERIAS(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_MATERIA VARCHAR(11) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Playlist de matérias pré-definidas';

CREATE TABLE ATIVIDADES (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TURMA INT(11) NOT NULL,
    ID_PROFESSOR INT(11) NOT NULL,
    ID_MATERIA INT(11) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    ATIVIDADE VARCHAR(255) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_IDTURMA_ATIVIDADES FOREIGN KEY (ID_TURMA) REFERENCES TURMAS (ID),
    CONSTRAINT FK_IDPROFESSOR_ATIVIDADES FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID),
    CONSTRAINT FK_IDMATERIA_ATIVIDADES FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Atividades em .pdf, .docx, etc, que estarão disponiveis na plataforma';

CREATE TABLE VIDEO_AULAS(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TURMA INT(11) NOT NULL,
    ID_PROFESSOR INT(11) NOT NULL,
    ID_MATERIA INT(11) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    VIDEO VARCHAR(255) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_IDTURMA_VIDEO FOREIGN KEY (ID_TURMA) REFERENCES TURMAS (ID),
    CONSTRAINT FK_IDPROFESSOR_VIDEO FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID),
    CONSTRAINT FK_IDMATERIA_VIDEO FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Vídeos aulas que estarão disponiveis na plataforma';