CREATE DATABASE `PAULINO` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE PAULINO;

CREATE TABLE TURMAS (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SERIE CHAR(20) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE PROFESSORES (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(160) NOT NULL,
    SENHA VARCHAR(16) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE DISCIPLINAS(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_DISCIPLINA VARCHAR(30) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE MATERIAS(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_DISCIPLINA INT(11) NOT NULL,
    NOME_MATERIA VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(160),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_IDDISCIPLINA_MATERIAS FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINAS (ID)
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE ATIVIDADES (
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TURMA INT(11) NOT NULL,
    ID_PROFESSOR INT(11) NOT NULL,
    ID_MATERIA INT(11) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    ATIVIDADE VARCHAR(255) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_IDTURMA_ATIVIDADES FOREIGN KEY (ID_TURMA) REFERENCES TURMAS (ID),
    CONSTRAINT FK_IDPROFESSOR_ATIVIDADES FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID),
    CONSTRAINT FK_IDMATERIA_ATIVIDADES FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID)
) CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE VIDEO_AULAS(
    ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TURMA INT(11) NOT NULL,
    ID_PROFESSOR INT(11) NOT NULL,
    ID_MATERIA INT(11) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    VIDEO VARCHAR(255) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT FK_IDTURMA_VIDEO FOREIGN KEY (ID_TURMA) REFERENCES TURMAS (ID),
    CONSTRAINT FK_IDPROFESSOR_VIDEO FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID),
    CONSTRAINT FK_IDMATERIA_VIDEO FOREIGN KEY (ID_MATERIA) REFERENCES MATERIAS (ID)
) CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO PROFESSORES (NOME, EMAIL, SENHA) VALUES ('Admin', 'admin@ead.com', 'admin');

INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("MATEMATICA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("PORTUGUES");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("SOCIOLOGIA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("HISTORIA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("GEOGRAFIA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("FILOSOFIA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("ED. FISICA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("FISICA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("QUIMICA");
INSERT INTO DISCIPLINAS (NOME_DISCIPLINA) VALUES ("INFORMATICA");

INSERT INTO TURMAS (SERIE) VALUES ("3 EM");
INSERT INTO TURMAS (SERIE) VALUES ("2 EM");
INSERT INTO TURMAS (SERIE) VALUES ("1 EM");
INSERT INTO TURMAS (SERIE) VALUES ("8 EF");
INSERT INTO TURMAS (SERIE) VALUES ("7 EF");
INSERT INTO TURMAS (SERIE) VALUES ("6 EF");
INSERT INTO TURMAS (SERIE) VALUES ("5 EF");
INSERT INTO TURMAS (SERIE) VALUES ("4 EF");
INSERT INTO TURMAS (SERIE) VALUES ("3 EF");
INSERT INTO TURMAS (SERIE) VALUES ("2 EF");
INSERT INTO TURMAS (SERIE) VALUES ("1 EF");